pretranslate:
  segments:
    ignore_patterns:
    - "{% .* %}"
    - "^layout: post"
    - "^(title|authors|date|description): "

  paths:
  - source: "src/site/content/en"
    include:
    - "accessible/**/index.md"