pretranslate:
  segments:
    ignore_patterns:
    - "{% ([a-zA-Z'\"\s])* %}"
    - "^(layout:.*)"
    - "^(title|authors|date|description): "

  paths:
  - source: "src/site/content/en"
    include:
    - "accessible/**/index.md"
