pretranslate:
  segments:
    ignore_patterns:
    - "{%\s?Aside\s?('[a-z]+')?\s?%}"
    - "{%\s?endAside\s?%}"
    - "Natywne"
    - "^(title|authors|date|description): "

  paths:
  - source: "src/site/content/en"
    include:
    - "accessible/**/index.md"
