pretranslate:
  segments:
    ignore_patterns:
    - "Native"
    - "{%\\s?([a-zA-Z0-9\\.\\-\\?\'\"\\s]*)\\s?%}"

  paths:
  - source: "src/site/content/en"
    include:
    - "accessible/**/index.md"
