name: Percy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm ci
      - name: Percy Test
        with:
          command: "npm run test:snapshots"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}